# Generated by Django 3.2.24 on 2024-04-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=500)),
                ('completed', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
